version: "3.7"
services:
  letmeask:
    image: letmeask
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: letmeask
    restart: unless-stopped
    ports:
      - 9090:3100
    volumes:
      - ./:/app
    environment:
        FIREBASE_API_KEY: 
        FIREBASE_AUTH_DOMAIN: 
        FIREBASE_DATABASE_URL: 
        FIREBASE_PROJECT_ID: 
        FIREBASE_STORAGE_BUCKET: 
        FIREBASE_SENDER_ID: 
        FIREBASE_APP_ID: 
